import './globals.css';
import Navbar from './components/NavBar';
import Header from './components/Header';
import { Comfortaa } from 'next/font/google';

const comfortaa = Comfortaa({
  subsets: ['latin'],
  display: 'swap',
  weight: ['300', '400', '500', '600', '700'], // pick what you need
  variable: '--font-sans', // <-- binds to your CSS variable
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`light ${comfortaa.variable}`}>
      <body>
        <Header />
        <Navbar />
        <main className="ml-40 p-8">
          {children}
        </main>
      </body>
    </html>
  );
}
