import './globals.css';
import Navbar from './components/NavBar';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <body>
        
        {children}
      </body>
    </html>
  );
}
