import './globals.css';
import Navbar from './components/NavBar';
import Header from './components/Header';
import { Comfortaa } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';

const comfortaa = Comfortaa({
  subsets: ['latin'],
  display: 'swap',
  weight: ['300', '400', '500', '600', '700'], // pick what you need
  variable: '--font-sans', // <-- binds to your CSS variable
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" className={`light ${comfortaa.variable}`}>
        <body>
          <Header></Header>
          <div className="bg-primary min-h-100">
            <Navbar></Navbar>
            <main className="ml-40 p-8 bg-background">{children}</main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
